name: Build, Push, and Deploy Docker Image

on:
  push:
    branches:
      - master  

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t 159914497254528/test-docker:latest .

      # Push the Docker image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push 159914497254528/test-docker:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-push-deploy

    steps:
      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
      
      - name: Deploy to EC2
        env:
          DOCKER_IMAGE: 159914497254528/test-docker:latest
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.61.7.249 << EOF
            cd /home/ubuntu/test-docker
            sudo docker-compose pull  # Pull the latest images
            sudo docker-compose down   # Stop and remove current containers
            sudo docker-compose up -d  # Recreate and start containers in detached mode
          EOF
